[2025-05-15T10:07:41.904+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sales_ingestion.convert_xlsx_to_csv manual__2025-05-15T10:07:41.168997+00:00 [queued]>
[2025-05-15T10:07:41.910+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sales_ingestion.convert_xlsx_to_csv manual__2025-05-15T10:07:41.168997+00:00 [queued]>
[2025-05-15T10:07:41.910+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T10:07:41.911+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2025-05-15T10:07:41.911+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T10:07:41.921+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): convert_xlsx_to_csv> on 2025-05-15 10:07:41.168997+00:00
[2025-05-15T10:07:41.924+0000] {standard_task_runner.py:55} INFO - Started process 194 to run task
[2025-05-15T10:07:41.926+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sales_ingestion', 'convert_xlsx_to_csv', 'manual__2025-05-15T10:07:41.168997+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/upload_csv_to_postgres.py', '--cfg-path', '/tmp/tmpj6a2a_79']
[2025-05-15T10:07:41.927+0000] {standard_task_runner.py:83} INFO - Job 28: Subtask convert_xlsx_to_csv
[2025-05-15T10:07:41.966+0000] {task_command.py:389} INFO - Running <TaskInstance: sales_ingestion.convert_xlsx_to_csv manual__2025-05-15T10:07:41.168997+00:00 [running]> on host 92d0d3de5da6
[2025-05-15T10:07:42.118+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sales_ingestion
AIRFLOW_CTX_TASK_ID=convert_xlsx_to_csv
AIRFLOW_CTX_EXECUTION_DATE=2025-05-15T10:07:41.168997+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-15T10:07:41.168997+00:00
[2025-05-15T10:07:42.123+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/upload_csv_to_postgres.py", line 10, in xlsx_to_csv
    df = pd.read_excel(xlsx_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 1233, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_openpyxl.py", line 521, in __init__
    import_optional_dependency("openpyxl")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/_optional.py", line 118, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2025-05-15T10:07:42.129+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=sales_ingestion, task_id=convert_xlsx_to_csv, execution_date=20250515T100741, start_date=20250515T100741, end_date=20250515T100742
[2025-05-15T10:07:42.138+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 28 for task convert_xlsx_to_csv (Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.; 194)
[2025-05-15T10:07:42.179+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-05-15T10:07:42.203+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
